INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100651,'Adolf-Klarenbach-Schule','Walther-Rathenau-Str. 15','Holthausen','G',313);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (170768,'Albrecht-Dürer-Schule','Fürstenwall 100','Unterbilk','BK',3592);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151919,'Alfred-Herrhausen-Schule','Carl-Friedrich-Goerdeler-Str. 21','Garath','S',325);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (150861,'Aloys-Odenthal-Schule','Diepenstr. 24','Gerresheim','G',179);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158598,'Anne-Frank-Realschule','Ackerstr. 174','Flingern-Nord','R',502);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164355,'Annette-von-Droste-Hülshoff-Gymnasium','Brucknerstr. 19','Benrath','GY',963);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100924,'Astrid-Lindgren-Schule','Leuthenstr. 50','Eller','G',281);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158690,'Benzenberg-Realschule','Siegburger Str. 38','Oberbilk','R',557);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (187689,'Berufskolleg Bachstraße','Bachstr. 8','Bilk','BK',2684);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100500,'Bonifatius-Schule','Fleher Str. 70','Bilk','G',341);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100705,'Brehm-Schule','Karl-Müller-Str. 25','Düsseltal','G',427);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (183088,'Carl-Benz-Realschule Oberkassel','Lewitstr. 2','Niederkassel','R',401);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (107062,'Carl-Sonnenschein-Schule','Gerresheimer Landstr. 89','Unterbach','G',110);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100420,'Carl-Sonnenschein-Schule','Graf-Recke-Str. 153','Düsseltal','G',351);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164392,'Cecilien-Gymnasium','Schorlemerstr. 99','Niederkassel','GY',956);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100183,'Christophorus-Schule','Werstener Friedhofstr. 10','Wersten','G',209);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164434,'Comenius-Gymnasium','Hansaallee 90','Oberkassel','GY',961);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164100,'Dieter-Forte-Gesamtschule','Heidelberger Str. 75','Eller','GE',1300);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100821,'Don-Bosco-Montessori-Schule','Salierstr. 37','Oberkassel','G',211);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136359,'Dumont-Lindemann-Schule','Weberstr. 3','Friedrichstadt','H',441);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (187690,'Elly-Heuss-Knapp-Schule','Siegburger Str. 137','Oberbilk','BK',2762);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100717,'Elsa-Brandström-Schule','An der Golzheimer Heide 120','Unterrath','G',223);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (101000,'Ferdinand-Heye-Schule','Heyestr. 91','Gerresheim','G',158);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100274,'Franz-Boehm-Schule','Kamper Weg 291','Vennhausen','G',177);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (188621,'Franz-Jürgens-Berufskolleg','Färberstr. 34','Bilk','BK',2309);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151830,'Franz-Marc-Schule','Lohbachweg 18','Gerresheim','S',172);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (107141,'Franz-Vaahsen-Schule','Grenzweg 12','Wittlaer','G',373);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158630,'Freiherr-vom-Stein-Realschule','Färberstr. 40','Bilk','R',369);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164537,'Friedrich-Rückert-Gymnasium','Rückertstr. 6','Rath','GY',743);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100687,'Friedrich-von-Bodelschwingh-Schule','Cimbernstr. 24','Oberkassel','G',322);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (107086,'Friedrich-von-Spee-Schule','Am Litzgraben 28A','Angermund','G',296);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136475,'Fritz-Henkel-Schule','Stettiner Str. 98','Garath','H',286);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164525,'Georg-Büchner-Gymnasium','Felix-Klein-Str. 3','Golzheim','GY',762);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (193770,'Georg-Schulhoff-Realschule','Kamper Weg 291','Vennhausen','R',632);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100766,'Gerhard-Tersteegen-Schule','Beckbuschstr. 2','Stockum','G',301);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (199916,'Gesamtschule Stettiner Str.','Stettiner Str. 98','Garath','GE',190);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164458,'Geschwister-Scholl-Gymnasium','Redinghovenstr. 41','Bilk','GY',979);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (101059,'GGS Adam-Stegerwald-Straße','Adam-Stegerwald-Str. 14','Garath','G',189);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100390,'GGS Am Köhnen','Am Köhnen 73','Hassels','G',173);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100225,'GGS Bingener Weg','Bingener Weg 10','Eller','G',221);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100389,'GGS Deutzer Straße','Deutzer Str. 102','Eller','G',122);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100470,'GGS Flurstraße','Flurstr. 59','Flingern-Nord','G',226);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (101047,'GGS Helmholtzstraße','Helmholtzstr. 16','Friedrichstadt','G',309);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100160,'GGS Kaiserswerth','Fliednerstr. 32','Kaiserswerth','G',332);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (107219,'GGS Knittkuhl','Am Mergelsberg 1','Knittkuhl','G',298);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100810,'GGS Konkordiastraße','Konkordiastr. 26','Unterbilk','G',254);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100950,'GGS Krahnenburgstraße','Krahnenburgstr. 15','Lichtenbroich','G',303);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100961,'GGS Kronprinzenstraße','Kronprinzenstr. 107','Unterbilk','G',267);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100936,'GGS Lennéstraße','Lennéstr. 5','Pempelfort','G',184);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100778,'GGS Lörick','Wickrather Str. 31','Lörick','G',237);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100894,'GGS Max-Halbe-Straße','Max-Halbe-Str. 14','Mörsenbroich','G',194);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100870,'GGS Neustrelitzer Straße','Neustrelitzer Str. 10','Garath','G',176);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100845,'GGS Richardstraße','Richardstr. 14','Eller','G',298);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100833,'GGS Rolandstraße','Rolandstr. 40','Golzheim','G',369);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100808,'GGS Sonnenstraße','Sonnenstr. 10','Oberbilk','G',310);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (101011,'GGS Stoffeler Straße','Stoffeler Str. 11','Oberbilk','G',248);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100791,'GGS Südallee','Südallee 100','Urdenbach','G',315);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100663,'GGS Unterrath','Beedstr. 31','Unterrath','G',107);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100330,'GGS Urdenbach','Garather Str. 16','Urdenbach','G',313);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100780,'GGS Vennhauser Allee','Vennhauser Allee 160-162','Vennhausen','G',179);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100869,'GGS Wrangelstraße','Wrangelstr. 40','Rath','G',199);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136505,'GHS Benrath','Melanchthonstr. 2','Benrath','H',322);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136384,'GHS Bernburger Straße','Bernburger Str. 44','Eller','H',332);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136281,'GHS Graf-Recke-Straße','Graf-Recke-Str. 230','Grafenberg','H',343);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164318,'Goethe-Gymnasium mit ehem. Rethel-Gymnasium','Lindemannstr. 57','Düsseltal','GY',926);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164446,'Görres-Gymnasium','Königsallee 57','Stadtmitte','GY',716);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100882,'Grundschule Schloss Benrath','Erich-Müller-Str. 31','Benrath','G',189);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100237,'Gumbertschule','Gumbertstr. 191','Eller','G',202);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100328,'Gutenberg-Schule','Grafenberger Allee 384','Grafenberg','G',443);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164513,'Gymnasium Gerresheim','Am Poth 60','Gerresheim','GY',968);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164409,'Gymnasium Koblenzer Straße','Theodor-Litt-Straße 2','Urdenbach','GY',877);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100015,'Gymnasium Schmiedestraße','Schmiedestr. 25','Oberbilk','GY',114);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100754,'Hanna-Zürndorfer-Schule','Benderstr. 78','Gerresheim','G',217);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (188232,'Heinrich-Heine-Gesamtschule','Graf-Recke-Str. 170','Mörsenbroich','GE',1255);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (101023,'Heinrich-Heine-Schule','Heerdter Landstr. 186','Heerdt','G',367);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (188086,'Heinrich-Hertz-Berufskolleg','Redinghovenstr. 16','Bilk','BK',2071);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100213,'Henri-Dunant-Schule','Rheindorfer Weg 20','Wersten','G',295);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100122,'Hermann-Gmeiner-Schule','Schillstr. 7','Hassels','G',183);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (163806,'Hermann-Harry-Schmitz-Weiterbildungskolleg -Abendrealschule','Emil-Barth-Str. 45','Garath','WB',306);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (189819,'Hulda-Pankok-Gesamtschule','Brinckmannstr. 16','Bilk','GE',1022);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164320,'Humboldt-Gymnasium','Pempelforter Str. 40','Pempelfort','GY',1220);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151804,'Jan-Wellem-Schule','Franklinstr. 5','Pempelfort','S',265);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100699,'Joachim-Neander-Schule','Rather Markt 2','Rath','G',286);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (191863,'Joseph-Beuys-Gesamtschule','Siegburger Str. 149','Oberbilk','GE',927);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158586,'Justus-von-Liebig-Realschule','Ottweilerstr. 20','Golzheim','R',520);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100020,'Kartause-Hain-Schule','Unterrather Str. 76','Unterrath','G',194);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100560,'KGS Einsiedelstraße','Einsiedelstr. 25','Benrath','G',223);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100535,'KGS Essener Straße','Essener Str. 1','Derendorf','G',240);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100493,'KGS Fleher Straße','Fleher Str. 213','Flehe','G',257);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100481,'KGS Florensstraße','Heinsenstr. 21','Hamm','G',151);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100468,'KGS Fuldaer Straße','Fuldaer Str. 33','Eller','G',202);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100316,'KGS Höhenstraße','Höhenstr. 5','Oberbilk','G',205);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100158,'KGS Josef-Kleesattel-Straße','Josef-Kleesattel-Str. 13','Garath','G',174);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100298,'KGS Lohausen','Im Grund 78','Lohausen','G',108);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100304,'KGS Mettmanner Straße','Hubbelrather Str. 13','Flingern-Süd','G',256);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100067,'KGS Niederkassel','Niederkasseler Str. 36','Niederkassel','G',341);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100092,'KGS Rather Kreuzweg','Rather Kreuzweg 21','Rath','G',150);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100171,'KGS Unter den Eichen','Unter den Eichen 26','Gerresheim','G',348);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136323,'KHS Itterstraße','Itterstr. 16','Holthausen','H',295);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164471,'Leibniz-Montessori-Gymnasium','Scharnhorststr. 8','Pempelfort','GY',739);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (187859,'Lessing-Berufskolleg','Ellerstr. 84-94','Oberbilk','BK',241);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164483,'Lessing-Gymnasium','Ellerstr. 84-94','Oberbilk','GY',681);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (186454,'Lore-Lorentz-Schule','Schloßallee 14','Eller','BK',1226);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164501,'Luisen-Gymnasium','Bastionstr. 24','Stadtmitte','GY',658);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (199606,'Maria-Montessori-Gesamtschule','Lindenstr. 140','Flingern-Nord','GE',548);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164379,'Marie-Curie-Gymnasium','Gräulinger Str. 15','Gerresheim','GY',1000);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100109,'Marien-Schule','Rheindorfer Weg 20','Wersten','G',340);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151932,'Martin-Luther-King-Schule','Schönaustr. 25','Gerresheim','S',162);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100730,'Martin-Luther-Schule','Gotenstr. 20','Bilk','G',194);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100742,'Matthias-Claudius-Schule','Bongardstr. 9','Pempelfort','G',320);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164495,'Max-Planck-Gymnasium','Koetschaustr. 36','Stockum','GY',915);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100572,'Max-Schule','Citadellstr. 2B','Altstadt','G',110);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (170793,'Max-Weber-Berufskolleg','Suitbertusstr. 163-165','Bilk','BK',2365);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (183635,'Montessori-Grundschule Emil-Barth-Straße','Emil-Barth-Str. 45','Garath','G',322);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100638,'Montessori-Grundschule Farnweg','Farnweg 10','Stockum','G',323);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (150850,'Montessori-Grundschule Lindenstraße','Lindenstr. 102','Flingern-Nord','G',405);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (186922,'Montessori-Hauptschule Hermannplatz','Lindenstr. 140','Flingern-Nord','H',39);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151889,'Mosaikschule','Am Massenberger Kamp 45','Wersten','S',175);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100444,'Paul-Klee-Schule','Gerresheimer Str. 34','Stadtmitte','G',208);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100079,'Paulusschule','Paulusplatz 1','Düsseltal','G',348);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158641,'Realschule Benrath','Hospitalstr. 45','Benrath','R',671);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158574,'Realschule Florastraße','Florastr. 69','Unterbilk','R',500);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158665,'Realschule Friedrichstadt','Luisenstr. 73','Friedrichstadt','R',479);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158616,'Realschule Golzheim','Tersteegenstr. 62','Golzheim','R',651);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100973,'Regenbogenschule','Jahnstr. 97','Friedrichstadt','G',97);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151865,'Rudolf-Hildebrand-Schule','Gotenstr. 20','Bilk','S',214);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (164343,'Schloß-Gymnasium Benrath','Hospitalstr. 45','Benrath','GY',724);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100675,'Selma Lagerlöf Schule','Schillstr. 7','Hassels','G',181);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100286,'St. Apollinaris Schule','Itterstr. 16','Holthausen','G',478);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100432,'St. Bruno-Schule','An der Golzheimer Heide 120','Unterrath','G',205);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100262,'St. Michael-Schule','Kempgensweg 65','Lierenfeld','G',154);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100596,'St. Rochus-Schule','Gneisenaustr. 60','Pempelfort','G',249);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136440,'St.-Benedikt-Schule','Charlottenstr. 110','Stadtmitte','H',352);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100547,'St.-Cäcilia-Schule','Erich-Müller-Str. 31','Benrath','G',139);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100584,'St.-Elisabeth-Schule','Buchenstr. 16','Reisholz','G',210);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100523,'St.-Franziskus-Schule','Herchenbachstr. 2','Mörsenbroich','G',349);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100250,'St.-Peter-Schule','Jahnstr. 97','Friedrichstadt','G',200);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100985,'Sternwartschule','Im Dahlacker 15','Bilk','G',224);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (151890,'Theodor-Andresen-Schule','Lohbachweg 16','Gerresheim','S',152);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100900,'Theodor-Heuss-Schule','Lützenkircher Str. 2','Wersten','G',169);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158689,'Theodor-Litt-Realschule','Theodor-Litt-Str. 5-11','Urdenbach','R',655);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158604,'Thomas-Edison-Realschule','Schlüterstr. 18-20','Flingern-Nord','R',551);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100602,'Thomas-Schule','Blumenthalstr. 11','Derendorf','G',207);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (100365,'Volker Rosin Schule','Arnstadter Weg 6-16','Vennhausen','G',251);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (170781,'Walter-Eucken-Berufskolleg','Suitbertusstr. 163-165','Bilk','BK',2483);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (170513,'Weiterbildungskolleg -Abendgymnasium-','Rückertstr. 6','Rath','WB',197);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (158550,'Werner-von-Siemens-Realschule','Rethelstr. 13','Düsseltal','R',663);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (107049,'Wichernschule','Brorsstr. 5','Unterbach','G',212);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (136566,'Wilhelm-Ferdinand-Schüßler-Tagesschule','Rather Kreuzweg 21','Rath','H',313);
INSERT INTO schulen(Schulnr,Name,Anschrift,Stadtteil,Schulform,Anzahl) VALUES (101060,'Willi-Fährmann-Schule','Ricarda-Huch-Str. 1','Garath','G',210);
